-- Cotizaciones (Abonados)
CREATE TABLE IF NOT EXISTS `quotations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quotation_number` VARCHAR(32) NOT NULL,
  `branch_office_id` INT NOT NULL,
  `rut` VARCHAR(32) NOT NULL,
  `customer` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `phone` VARCHAR(64) DEFAULT NULL,
  `activity` VARCHAR(255) DEFAULT NULL,
  `address` VARCHAR(512) DEFAULT NULL,
  `region_id` INT DEFAULT NULL,
  `commune_id` INT DEFAULT NULL,
  `period` VARCHAR(7) NOT NULL,
  `renew_mode` TINYINT NOT NULL DEFAULT 1 COMMENT '1=fija 2=mes a mes',
  `status_id` TINYINT NOT NULL DEFAULT 1 COMMENT '1=borrador 2=enviada 3=convertida 4=anulada',
  `chip_id` INT DEFAULT 0,
  `subtotal` INT NOT NULL DEFAULT 0,
  `tax` INT NOT NULL DEFAULT 0,
  `total` INT NOT NULL DEFAULT 0,
  `last_sent_at` DATETIME DEFAULT NULL,
  `last_sent_channel` VARCHAR(32) DEFAULT NULL,
  `converted_dte_id` INT DEFAULT NULL,
  `source_quotation_id` INT DEFAULT NULL,
  `added_date` DATETIME DEFAULT NULL,
  `updated_date` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_quotations_number` (`quotation_number`),
  KEY `idx_quotations_period` (`period`),
  KEY `idx_quotations_rut` (`rut`),
  KEY `idx_quotations_status` (`status_id`),
  KEY `idx_quotations_renew` (`renew_mode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `quotation_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quotation_id` INT NOT NULL,
  `line_number` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `unit_amount` INT NOT NULL DEFAULT 0,
  `total_amount` INT NOT NULL DEFAULT 0,
  `description` VARCHAR(500) NOT NULL,
  `dsc_item` VARCHAR(500) DEFAULT NULL,
  `item_code` VARCHAR(64) DEFAULT NULL,
  `item_name` VARCHAR(255) DEFAULT NULL,
  `unit_measure` VARCHAR(32) DEFAULT NULL,
  `discount_amount` INT NOT NULL DEFAULT 0,
  `status_id` INT NOT NULL DEFAULT 1,
  `added_date` DATETIME DEFAULT NULL,
  `updated_date` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_qi_quotation` (`quotation_id`),
  CONSTRAINT `fk_qi_quotation` FOREIGN KEY (`quotation_id`)
    REFERENCES `quotations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
