CREATE TABLE IF NOT EXISTS `received_inbox` (
  `id` int NOT NULL AUTO_INCREMENT,
  `rut` varchar(32) NOT NULL,
  `supplier` varchar(255) DEFAULT NULL,
  `branch_office_id` int DEFAULT 0,
  `folio` int NOT NULL,
  `dte_type_id` int NOT NULL,
  `status_id` int NOT NULL DEFAULT 1,
  `subtotal` int DEFAULT 0,
  `tax` int DEFAULT 0,
  `total` int DEFAULT 0,
  `environment` varchar(32) DEFAULT NULL,
  `document_status` varchar(64) DEFAULT NULL,
  `sii_status` varchar(64) DEFAULT NULL,
  `acknowledgment_status` varchar(64) DEFAULT NULL,
  `track_id` bigint DEFAULT NULL,
  `document_date` date DEFAULT NULL,
  `added_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_received_inbox_folio_rut_type` (`folio`, `rut`, `dte_type_id`),
  KEY `idx_received_inbox_added_date` (`added_date`),
  KEY `idx_received_inbox_status` (`status_id`),
  KEY `idx_received_inbox_rut` (`rut`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
