-- Carga masiva delivery_address_tags (datos desde planillas capturadas).
-- Requisitos: existan filas en `regions` y `communes` cuyos textos coincidan
-- (o variantes listadas en los IN (...)). Revise con:
--   SELECT id, region FROM regions ORDER BY 1;
--   SELECT c.id, c.commune, r.region FROM communes c JOIN regions r ON r.id = c.region_id ORDER BY r.region, c.commune;
--
-- Si alguna subconsulta devuelve NULL, MySQL rechazará la fila: ajuste el IN (...) a su catálogo.
-- Ejecute sobre tabla vacía o borre ids conflictivos antes.

SET NAMES utf8mb4;

-- Opcional: TRUNCATE TABLE delivery_address_tags;

INSERT INTO delivery_address_tags (
    id,
    region_id,
    commune_id,
    branch_office,
    address,
    supervisor_rut,
    supervisor,
    phone,
    company_name,
    company_rut,
    company_phone,
    company_address,
    added_date,
    updated_date
) VALUES
(
    1,
    (SELECT r.id FROM regions r WHERE r.region IN ('Antofagasta', 'II Región de Antofagasta') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Antofagasta', 'II Región de Antofagasta') AND c.commune IN ('Antofagasta') LIMIT 1),
    'UNIMARC EL PAMPINO',
    'Jose Santos Ossa 2350, Antofagasta',
    '1003452-4',
    'Fidelia del Carmen Contreras Gonzalez',
    '944320323',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    2,
    (SELECT r.id FROM regions r WHERE r.region IN ('Antofagasta', 'II Región de Antofagasta') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Antofagasta', 'II Región de Antofagasta') AND c.commune IN ('Antofagasta') LIMIT 1),
    'UNIMARC EL PARQUE',
    'Av. Jose Miguel Carrera 1527, Antofagasta',
    '1003452-4',
    'Fidelia del Carmen Contreras Gonzalez',
    '944320323',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    3,
    (SELECT r.id FROM regions r WHERE r.region IN ('Coquimbo', 'IV Región de Coquimbo') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Coquimbo', 'IV Región de Coquimbo') AND c.commune IN ('La Serena') LIMIT 1),
    'UNIMARC LA SERENA',
    'Avda. Brasil 756, La Serena',
    '1092451-3',
    'Maria Estela Perez Peralta',
    '953410605',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    4,
    (SELECT r.id FROM regions r WHERE r.region IN ('Coquimbo', 'IV Región de Coquimbo') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Coquimbo', 'IV Región de Coquimbo') AND c.commune IN ('Ovalle') LIMIT 1),
    'UNIMARC OVALLE',
    'Libertad 230, Ovalle',
    '15848135-6',
    'Sofia Alejandra Mundaca Mundaca',
    '954238971',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    7,
    (SELECT r.id FROM regions r WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') AND c.commune IN ('Quillota') LIMIT 1),
    'UNIMARC QUILLOTA',
    'Bernardo O''Higgins 34, Quillota',
    '10137545-5',
    'Margarita Del Carmen Contreras Parec',
    '97248828',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    8,
    (SELECT r.id FROM regions r WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') AND c.commune IN ('Viña del Mar', 'Vina del Mar') LIMIT 1),
    'STA ISABEL REÑACA',
    'Rafael Sotomayor 230, Viña del Mar',
    '14487138-8',
    'Evelyn Damarys Molina Saavedra',
    '95446888',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    9,
    (SELECT r.id FROM regions r WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') AND c.commune IN ('Valparaíso', 'Valparaiso') LIMIT 1),
    'STA ISABEL LOS CARRERAS',
    'Portales 770, Valparaiso',
    '09134412-2',
    'Gladys Antonia Villegas Alvarez',
    '95425334',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    16,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('Maipú', 'Maipu') LIMIT 1),
    'ALVI MAIPU',
    'Los Pajaritos 1631, Maipu',
    '18451383-1',
    'Marcelo Inzunza [Supervisor]',
    '988454901',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    17,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('Providencia') LIMIT 1),
    'UNIMARC FCO BILBAO',
    'Avda. Francisco Bilbao 2850, Providencia',
    '21902443-6',
    'David Wilder Gomez Figueroa',
    '942998971',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    22,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('Santiago') LIMIT 1),
    'TOTTUS NATANIEL',
    'Nataniel Cox 620, Santiago',
    '21902443-6',
    'David Wilder Gomez Figueroa',
    '942998971',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    25,
    (SELECT r.id FROM regions r WHERE r.region IN ('Ñuble', 'Nuble', 'XVI Región de Ñuble') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Ñuble', 'Nuble', 'XVI Región de Ñuble') AND c.commune IN ('Chillán', 'Chillan') LIMIT 1),
    'UNIMARC CHILLAN',
    'Arauco 755, Chillan',
    '15757306-3',
    'David de Jesus Contreras Martinez',
    '981188424',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    32,
    (SELECT r.id FROM regions r WHERE r.region IN ('Los Lagos', 'X Región de Los Lagos') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Los Lagos', 'X Región de Los Lagos') AND c.commune IN ('Osorno') LIMIT 1),
    'LIDER OSORNO',
    'Errazuriz 1318, Osorno',
    '1712511-3',
    'Eliana Marcela Almonacid Avendaño',
    '98435532',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    42,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('San Miguel') LIMIT 1),
    'LIDER GRAN AVENIDA',
    'G. AV. JOSE MIGUEL CARRERA #4004, San Miguel',
    '08820315-1',
    'Benjamín Leonardo Bruyer Gonzalez',
    '94298871',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    65,
    (SELECT r.id FROM regions r WHERE r.region IN ('Los Lagos', 'X Región de Los Lagos') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Los Lagos', 'X Región de Los Lagos') AND c.commune IN ('Puerto Montt') LIMIT 1),
    'LIDER PUERTO MONTT',
    'Balmaceda, Nro. 212, Puerto Montt',
    '127834958-6',
    'Eliana Marcela Alburquerque Avendaño',
    '945714126',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    85,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('Santiago') LIMIT 1),
    'OFICINA',
    'Matucana 40, Estación Central',
    '18451383-1',
    'Marcelo Alejandro Inzunza Gonzalez',
    NULL,
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    97,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('Santiago') LIMIT 1),
    'UNIV BERNARDO OHIGGINS',
    'GENERAL GANA #1570 Block #SUBT. DEPTO. #2Y-3 CIUDAD SANTIAGO',
    '08820315-1',
    'Benjamin Leonardo Bruyer Gonzalez',
    '942547663',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    99,
    (SELECT r.id FROM regions r WHERE r.region IN ('Atacama', 'III Región de Atacama') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Atacama', 'III Región de Atacama') AND c.commune IN ('Copiapó', 'Copiapo') LIMIT 1),
    'LIDER COPIAPO',
    'Chacabuco 120, Copiapó',
    '24773648-4',
    'Delsy Zamira Hernandez Arias',
    '985020991',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    100,
    (SELECT r.id FROM regions r WHERE r.region IN ('Maule', 'VII Región del Maule') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Maule', 'VII Región del Maule') AND c.commune IN ('Talca') LIMIT 1),
    'STRIP TALCA',
    'CALLE 2 NORTE #3230 CIUDAD TALCA COMUNA TALCA REGION DEL MAULE',
    '18228287-1',
    'Anibal Isaac Alvear Saavedra',
    '974032165',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    101,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('Peñalolén', 'Peñalolen') LIMIT 1),
    'LIDER QUILIN',
    'AV. AMERICO VESPUCIO #3100 CIUDAD SANTIAGO COMUNA PEÑALOLEN REG',
    '21002440-6',
    'David Wilder Gomez Figueroa',
    '942800971',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    102,
    (SELECT r.id FROM regions r WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') AND c.commune IN ('Viña del Mar', 'Vina del Mar') LIMIT 1),
    'STA ISABEL VILLANELO',
    'AV VALPARAISO E. VILLANELO #236 CIUDAD VALPARAISO COMUNA VINA DEL',
    '15498400-3',
    'Silvana Vanessa Molina Saavedra',
    '985185848',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    103,
    (SELECT r.id FROM regions r WHERE r.region IN ('Biobío', 'Biobio', 'VIII Región del Biobío') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Biobío', 'Biobio', 'VIII Región del Biobío') AND c.commune IN ('Los Ángeles', 'Los Angeles') LIMIT 1),
    'TOTTUS LOS ANGELES',
    'Av. ALEMANIA 831, Los Angeles',
    '14584420-1',
    'Nayade Macarena Valverde Valverde',
    '941491729',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    105,
    (SELECT r.id FROM regions r WHERE r.region IN ('Biobío', 'Biobio', 'VIII Región del Biobío') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Biobío', 'Biobio', 'VIII Región del Biobío') AND c.commune IN ('Los Ángeles', 'Los Angeles') LIMIT 1),
    'LIDER LOS ANGELES',
    'Av. Ricardo Vicuña 284, Los Angeles',
    '16062562-7',
    'Pamela Soraya Morales Medina',
    '942604652',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    106,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('Estación Central', 'Estacion Central') LIMIT 1),
    'LIDER ALAMEDA',
    'Av. Padre alberto hurtado 4060, Estación Central',
    '08820315-1',
    'Benjamin Leonardo Bruyer Gonzalez',
    '942547663',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    107,
    (SELECT r.id FROM regions r WHERE r.region IN ('Los Lagos', 'X Región de Los Lagos') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Los Lagos', 'X Región de Los Lagos') AND c.commune IN ('Osorno') LIMIT 1),
    'EDIFICIO BUHLER',
    'Avda. Guillermo Buhler #2005, Osorno',
    '17125110-3',
    'Debora Eunice Filun Filun',
    '984365321',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    109,
    (SELECT r.id FROM regions r WHERE r.region IN ('Biobío', 'Biobio', 'VIII Región del Biobío') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Biobío', 'Biobio', 'VIII Región del Biobío') AND c.commune IN ('Los Ángeles', 'Los Angeles') LIMIT 1),
    'JUMBO LOS ANGELES',
    'AV. ERCILLA #1190, LOS ANGELES, REGION DEL BIO BIO',
    '17551177-6',
    'Valeria Nicole Zagal Rodriguez',
    '931655721',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    110,
    (SELECT r.id FROM regions r WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') AND c.commune IN ('Quillota') LIMIT 1),
    'LIDER QUILLOTA',
    'AV. 21 DE MAYO RECINTO ESTACION COMUNA QUILLOTA REGION DE VALPA',
    '25707126-8',
    'Fabiana Cristina Montaño Azuaje',
    '949818234',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    111,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('Las Condes') LIMIT 1),
    'STA ISABEL CANTAGALLO',
    'LAS CONDES 12207 Block #01 DEPTO. #0F. COMUNA LAS CONDES REGION ME',
    '28888888-8',
    'Marcelo Inzunza (Supervisor)',
    '968454901',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    112,
    (SELECT r.id FROM regions r WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Valparaíso', 'Valparaiso', 'V Región de Valparaíso') AND c.commune IN ('Valparaíso', 'Valparaiso') LIMIT 1),
    'STA ISABEL PEDRO MONTT',
    'Av Pedro Montt 1845, Valparaíso',
    '10033741-K',
    'Marcelo Alejandro Inzunza Gonzalez',
    '968454901',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    113,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('Lo Prado') LIMIT 1),
    'LIDER SAN PABLO',
    'Neptuno N°720, Lo Prado',
    '08820315-1',
    'Benjamin Leonardo Bruyer Gonzalez',
    '942547663',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    114,
    (SELECT r.id FROM regions r WHERE r.region IN ('Libertador General Bernardo O''Higgins', 'Libertador General Bernardo OHiggins', 'VI Región del Libertador General Bernardo O''Higgins') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Libertador General Bernardo O''Higgins', 'Libertador General Bernardo OHiggins', 'VI Región del Libertador General Bernardo O''Higgins') AND c.commune IN ('San Vicente de Tagua Tagua', 'San Vicente') LIMIT 1),
    'LIDER SAN VICENTE',
    'Calle Germán Riesco 510, Esquina Diego Portales, San Vicente de Tagua Tagua',
    '28888888-8',
    'Marcelo Inzunza (Supervisor)',
    '968454901',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    115,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('Santiago') LIMIT 1),
    'LIDER 10 DE JULIO',
    'Diez de julio 1525, Santiago',
    '08820315-1',
    'Benjamin Leonardo Bruyer Gonzalez',
    '942547663',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    116,
    (SELECT r.id FROM regions r WHERE r.region IN ('Atacama', 'III Región de Atacama') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Atacama', 'III Región de Atacama') AND c.commune IN ('General Lagos', 'Vallenar') LIMIT 1),
    'TOTTUS VALLENAR',
    'Brasil 941, Vallenar',
    '08820315-1',
    'Benjamin Leonardo Bruyer Gonzalez',
    '942547663',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
),
(
    117,
    (SELECT r.id FROM regions r WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') LIMIT 1),
    (SELECT c.id FROM communes c INNER JOIN regions r ON r.id = c.region_id WHERE r.region IN ('Metropolitana de Santiago', 'Región Metropolitana de Santiago', 'RM') AND c.commune IN ('Puente Alto') LIMIT 1),
    'LIDER CORDILLERA',
    'Avda Los Toros 05441, Puente Alto',
    '16462551-6',
    'Cintia Beatriz Gonzalez Orellana',
    '984911692',
    'JIS Parking SpA',
    '76.063.822-6',
    '+569 68454900',
    'Matucana 40, Est Central, Santiago',
    NOW(),
    NOW()
);
