-- Tipos de documento referenciado (códigos SII y códigos internos ChileCompra / logística).
-- El valor en `code` es el que se guarda en `dte_references.reference_type_id`.

CREATE TABLE IF NOT EXISTS `reference_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(32) NOT NULL COMMENT 'Código enviado en reference_type_id',
  `description` VARCHAR(512) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reference_types_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `reference_types` (`code`, `description`, `sort_order`) VALUES
('30', 'Factura', 10),
('32', 'Factura de ventas y servicios no afectos o exentos de IVA', 20),
('33', 'Factura electrónica', 30),
('34', 'Factura no afecta o exenta', 40),
('35', 'Boleta', 50),
('38', 'Boleta exenta', 60),
('39', 'Boleta electrónica', 70),
('40', 'Liquidación factura', 80),
('41', 'Boleta exenta electrónica', 90),
('43', 'Liquidación factura electrónica', 100),
('45', 'Factura de compra', 110),
('46', 'Factura de compra electrónica', 120),
('48', 'Pago electrónico', 130),
('50', 'Guía de despacho', 140),
('52', 'Guía de despacho electrónica', 150),
('55', 'Nota de débito', 160),
('56', 'Nota de débito electrónica', 170),
('60', 'Nota de crédito', 180),
('61', 'Nota de crédito electrónica', 190),
('101', 'Factura de exportación', 200),
('103', 'Liquidación', 210),
('104', 'Nota de débito de exportación', 220),
('106', 'Nota de crédito de exportación', 230),
('108', 'Solicitud registro de factura (SRF)', 240),
('110', 'Factura de exportación electrónica', 250),
('111', 'Nota de débito de exportación electrónica', 260),
('112', 'Nota de crédito de exportación electrónica', 270),
('801', 'Orden de compra', 280),
('802', 'Nota de pedido', 290),
('803', 'Contrato', 300),
('804', 'Resolución', 310),
('805', 'Proceso ChileCompra', 320),
('806', 'Ficha ChileCompra', 330),
('807', 'DUS', 340),
('808', 'B/L (conocimiento de embarque)', 350),
('809', 'AWB (Air Way Bill)', 360),
('810', 'MIC/DTA', 370),
('811', 'Carta de porte', 380),
('812', 'Resolución del SNA donde califica servicios de exportación', 390),
('813', 'Pasaporte', 400),
('814', 'Certificado de depósito bolsa prod. Chile', 410),
('815', 'Vale de prenda bolsa prod. Chile', 420),
('901', 'Factura de ventas a empresas del territorio preferencial', 430),
('904', 'Factura de traspaso', 440),
('909', 'Facturas venta módulo zona franca', 450),
('910', 'Solicitud traslado zona franca (Z)', 460),
('911', 'Declaración de ingreso a zona franca primaria', 470),
('914', 'Declaración de ingreso (DIN)', 480),
('EM', 'Entrada de mercadería (EM)', 490),
('HEM', 'Hoja de entrada de materiales (HEM)', 500),
('HES', 'Hoja de entrada de servicios (HES)', 510),
('MLE', 'Modalidad libre elección (MLE)', 520),
('RC', 'Recepción Conforme (RC)', 530),
('RDM', 'Recepción de material/mercadería (RDM)', 540);
